esphome:
  name: toilet-device
  friendly_name: Toilet Device

esp8266:
  board: esp01_1m
  restore_from_flash: True

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4Ovo+/4ZKrcAeaZC7IPI574VQrmSC6WQWbwtSBBQo+Q="

ota:
  - platform: esphome
    password: "133755a618a8aa70d3cdfcc798c505a4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Toilet-Device Fallback Hotspot"
    password: "FcK2gDOu12MB"

captive_portal:

# PRODINo WIFI-ESP WROOM-02 V1 settings
globals: # Create global variable to be used later on
  - id: is_night_time # Store state of day (false) or night (true)
    type: bool
    restore_value: no
    initial_value: 'false'

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

mcp23s08:
  - id: mcp23s08_hub
    cs_pin: GPIO15
    deviceaddress: 0

switch:
  - platform: template
    id: night_time
    name: "Night switch"
    lambda: |-
      return id(is_night_time);
    turn_on_action:
      - logger.log: "Night time swithch is on"
      - light.control:
          id: main_light
          brightness: 50%
      - lambda: |-
          id(is_night_time) = true; // Night time is set
    turn_off_action:
      - logger.log: "Night time swithch is off"
      - light.control:
          id: main_light
          brightness: 100%
      - lambda: |-
          id(is_night_time) = false; // Day time is set

  - platform: gpio
    id: relay_fan
    name: "Fan"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 4
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay_busy_light
    name: "Busy Light"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 5
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay3
    name: "RELAY3"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 6
      mode: OUTPUT
      inverted: False

  - platform: gpio
    id: relay4
    name: "RELAY4"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 7
      mode: OUTPUT
      inverted: False

binary_sensor:
  - platform: gpio
    id: pir_sensor
    name: "PIR Sensor"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 0
      mode: INPUT
      inverted: True
    on_state:
      - script.execute: light_timer

  - platform: gpio
    id: door_sensor
    name: "Door Sensor"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 1
      mode: INPUT
      inverted: True
  #   on_press:

  - platform: gpio
    id: fan_button
    name: "Fan Button"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 2
      mode: INPUT
      inverted: True
    on_press:
      - script.execute: fan_timer

  - platform: gpio
    id: input4
    name: "INPUT4"
    pin:
      mcp23xxx: mcp23s08_hub
      number: 3
      mode: INPUT
      inverted: True

# >>> Tiolet devices logic
output:
  - platform: esp8266_pwm
    id: pwm_light
    pin: GPIO5
    frequency: 1000 Hz

light:
  - platform: monochromatic
    name: "Main Light"
    id: main_light
    output: pwm_light
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - script.execute: light_timer

script:
  - id: light_timer
    mode: restart
    then:
      - switch.turn_on: relay_busy_light
      - light.turn_on:
          id: main_light
          transition_length: 3s
      - delay: 2min #10s
      - light.turn_off:
          id: main_light
          transition_length: 60s #10s 
      - switch.turn_off: relay_busy_light

  - id: fan_timer
    mode: restart
    then:
      - switch.turn_on: relay_fan
      - delay: 30min
      - switch.turn_off: relay_fan
